/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.controller.RoadTripsController;
import br.uefs.ecomp.RoadTrips.exceptions.CidadeNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.exceptions.DataNotFoundException;
import br.uefs.ecomp.RoadTrips.exceptions.EstradaDuplicadaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import br.uefs.ecomp.RoadTrips.model.Cidade;
import br.uefs.ecomp.RoadTrips.model.Interseccao;
import br.uefs.ecomp.RoadTrips.model.Ponto;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import java.lang.reflect.Array;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_USUARIO_RealizarViagem extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_USUARIO_RealizarViagem(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
        preencheCidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelCidadeInicial = new javax.swing.JLabel();
        jComboBoxCidadeFinal = new javax.swing.JComboBox<>();
        jComboBoxCidadeInicial = new javax.swing.JComboBox<>();
        jLabelCidadeFinal = new javax.swing.JLabel();
        jButtonGerarViagem = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Gerar Viagem");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelCidadeInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidadeInicial.setText("Ponto de Partida:");
        jPanel2.add(jLabelCidadeInicial);
        jLabelCidadeInicial.setBounds(30, 20, 120, 14);

        jPanel2.add(jComboBoxCidadeFinal);
        jComboBoxCidadeFinal.setBounds(240, 40, 190, 20);

        jComboBoxCidadeInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeInicialActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCidadeInicial);
        jComboBoxCidadeInicial.setBounds(30, 40, 180, 20);

        jLabelCidadeFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidadeFinal.setText("Ponto Destino:");
        jPanel2.add(jLabelCidadeFinal);
        jLabelCidadeFinal.setBounds(240, 20, 120, 14);

        jButtonGerarViagem.setText("Gerar Viagem");
        jButtonGerarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarViagemActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGerarViagem);
        jButtonGerarViagem.setBounds(273, 340, 150, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    public void preencheCidades(){
        jComboBoxCidadeInicial.removeAllItems();
        jComboBoxCidadeInicial.addItem("<Selecionar Opção>");
        jComboBoxCidadeFinal.removeAllItems();
        jComboBoxCidadeFinal.addItem("<Selecionar Opção>");
        
        Iterator itr = facade.iteratorTodasCidade();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Cidade){
                Cidade cidade = (Cidade)o;
                jComboBoxCidadeInicial.addItem(cidade.getNome());
                jComboBoxCidadeFinal.addItem(cidade.getNome());
            }
            else{
                Interseccao interseccao = (Interseccao)o;
                jComboBoxCidadeInicial.addItem(interseccao.getNome());
                jComboBoxCidadeFinal.addItem(interseccao.getNome());
            }
        }
    }
    
    
    private void jComboBoxCidadeInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeInicialActionPerformed
        
    }//GEN-LAST:event_jComboBoxCidadeInicialActionPerformed

    private void jButtonGerarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarViagemActionPerformed
        Ponto a = null, b = null;
        
        Iterator itr = facade.iteratorTodasCidade();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Cidade){
                Cidade cidade = (Cidade)o;
                if(jComboBoxCidadeInicial.getSelectedItem().equals(cidade.getNome())){
                    a = cidade;
                }
                if(jComboBoxCidadeFinal.getSelectedItem().equals(cidade.getNome())){
                    b = cidade;
                }
            }
            else{
                Interseccao interseccao = (Interseccao)o;
                if(jComboBoxCidadeInicial.getSelectedItem().equals(interseccao.getNome())){
                    a = interseccao;
                }
                if(jComboBoxCidadeFinal.getSelectedItem().equals(interseccao.getNome())){
                    b = interseccao;
                }
            }
        }
        
    }//GEN-LAST:event_jButtonGerarViagemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarViagem;
    private javax.swing.JComboBox<String> jComboBoxCidadeFinal;
    private javax.swing.JComboBox<String> jComboBoxCidadeInicial;
    private javax.swing.JLabel jLabelCidadeFinal;
    private javax.swing.JLabel jLabelCidadeInicial;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
