/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.exceptions.UsuarioDuplicadoException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_LOGIN_CadastrarUsuario extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_LOGIN_CadastrarUsuario(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonCadastrarUsuario = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Cadastrar Usuario");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNomeUsuario.setText("Nome do Usuário:");
        jPanel2.add(jLabelNomeUsuario);
        jLabelNomeUsuario.setBounds(20, 20, 120, 14);
        jPanel2.add(jTextFieldNomeUsuario);
        jTextFieldNomeUsuario.setBounds(20, 40, 420, 20);

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLogin.setText("Login:");
        jPanel2.add(jLabelLogin);
        jLabelLogin.setBounds(20, 70, 40, 14);
        jPanel2.add(jTextFieldLogin);
        jTextFieldLogin.setBounds(20, 90, 200, 20);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSenha.setText("Senha:");
        jPanel2.add(jLabelSenha);
        jLabelSenha.setBounds(230, 70, 80, 14);
        jPanel2.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(230, 90, 210, 20);

        jButtonCadastrarUsuario.setText("Cadastrar Usuário");
        jButtonCadastrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCadastrarUsuario);
        jButtonCadastrarUsuario.setBounds(293, 350, 140, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarUsuarioActionPerformed
        String nome = jTextFieldNomeUsuario.getText().trim();
        String login = jTextFieldLogin.getText().trim();
        String senha = jPasswordFieldSenha.getText();

        try {
            facade.inserirUsuario(nome, login, senha);
            JOptionPane.showMessageDialog(rootPane, "Usuario cadastrado com sucesso!");
            this.doDefaultCloseAction();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(RoadTrips_LOGIN_CadastrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(RoadTrips_LOGIN_CadastrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UsuarioDuplicadoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jButtonCadastrarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarUsuario;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
