/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.exceptions.CidadeDuplicadaException;
import br.uefs.ecomp.RoadTrips.exceptions.CidadeNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natália Rosa e Adriel Brito
 */
public class RoadTrips_ADM_EditarCidade extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     * @param facade Recebe a fachada do programa.
     */
    public RoadTrips_ADM_EditarCidade(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelArea = new javax.swing.JLabel();
        jTextFieldArea = new javax.swing.JTextField();
        jLabelPopulacao = new javax.swing.JLabel();
        jTextFieldPopulacao = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPaneDescricao = new javax.swing.JScrollPane();
        jTextDescricao = new javax.swing.JTextArea();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelLocalParaComer = new javax.swing.JLabel();
        jTextFieldNomeDoLocal = new javax.swing.JTextField();
        jTextFieldEnderecoLocalComer = new javax.swing.JTextField();
        jTextFieldLatitude = new javax.swing.JTextField();
        jTextFieldLongitude = new javax.swing.JTextField();
        jLabelLongitude = new javax.swing.JLabel();
        jButtonAdicionarLocal = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelLatitude = new javax.swing.JLabel();
        jButtonCadastrarCidade = new javax.swing.JButton();
        jScrollPaneLocaisParaComer = new javax.swing.JScrollPane();
        jTableLocaisParaComer = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Cadastrar Cidade");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidade.setText("Cidade:");
        jPanel2.add(jLabelCidade);
        jLabelCidade.setBounds(20, 20, 50, 14);
        jPanel2.add(jTextFieldCidade);
        jTextFieldCidade.setBounds(20, 40, 290, 20);

        jLabelArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelArea.setText("Área:");
        jPanel2.add(jLabelArea);
        jLabelArea.setBounds(20, 70, 40, 14);
        jPanel2.add(jTextFieldArea);
        jTextFieldArea.setBounds(20, 90, 200, 20);

        jLabelPopulacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPopulacao.setText("População:");
        jPanel2.add(jLabelPopulacao);
        jLabelPopulacao.setBounds(240, 70, 80, 14);
        jPanel2.add(jTextFieldPopulacao);
        jTextFieldPopulacao.setBounds(240, 90, 200, 20);

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDescricao.setText("Descrição:");
        jPanel2.add(jLabelDescricao);
        jLabelDescricao.setBounds(20, 170, 80, 14);

        jTextDescricao.setColumns(20);
        jTextDescricao.setRows(5);
        jScrollPaneDescricao.setViewportView(jTextDescricao);

        jPanel2.add(jScrollPaneDescricao);
        jScrollPaneDescricao.setBounds(20, 190, 270, 50);

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCodigo.setText("Código:");
        jPanel2.add(jLabelCodigo);
        jLabelCodigo.setBounds(320, 20, 60, 14);

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(320, 40, 120, 20);

        jLabelLocalParaComer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLocalParaComer.setText("Locais Para Comer:");
        jPanel2.add(jLabelLocalParaComer);
        jLabelLocalParaComer.setBounds(20, 250, 140, 14);

        jTextFieldNomeDoLocal.setText("Nome do Local");
        jTextFieldNomeDoLocal.setToolTipText("");
        jTextFieldNomeDoLocal.setEnabled(false);
        jPanel2.add(jTextFieldNomeDoLocal);
        jTextFieldNomeDoLocal.setBounds(20, 270, 170, 20);

        jTextFieldEnderecoLocalComer.setText("Endereço do Local");
        jTextFieldEnderecoLocalComer.setEnabled(false);
        jPanel2.add(jTextFieldEnderecoLocalComer);
        jTextFieldEnderecoLocalComer.setBounds(210, 270, 170, 20);

        jTextFieldLatitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLatitudeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLatitude);
        jTextFieldLatitude.setBounds(20, 140, 200, 20);
        jPanel2.add(jTextFieldLongitude);
        jTextFieldLongitude.setBounds(240, 140, 200, 20);

        jLabelLongitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLongitude.setText("Longitude:");
        jPanel2.add(jLabelLongitude);
        jLabelLongitude.setBounds(240, 120, 80, 14);

        jButtonAdicionarLocal.setText("+");
        jButtonAdicionarLocal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarLocal.setEnabled(false);
        jButtonAdicionarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarLocalActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdicionarLocal);
        jButtonAdicionarLocal.setBounds(390, 270, 50, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar);
        jButtonSalvar.setBounds(370, 360, 73, 23);

        jLabelLatitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLatitude.setText("Latitude:");
        jPanel2.add(jLabelLatitude);
        jLabelLatitude.setBounds(20, 120, 70, 14);

        jButtonCadastrarCidade.setText("Cadastrar Cidade");
        jButtonCadastrarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarCidadeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCadastrarCidade);
        jButtonCadastrarCidade.setBounds(300, 210, 140, 23);

        jTableLocaisParaComer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço"
            }
        ));
        jScrollPaneLocaisParaComer.setViewportView(jTableLocaisParaComer);

        jPanel2.add(jScrollPaneLocaisParaComer);
        jScrollPaneLocaisParaComer.setBounds(20, 300, 420, 50);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarLocalActionPerformed
        String nomeLocalComer = jTextFieldNomeDoLocal.getText().trim();
        String enderecoLocalComer = jTextFieldEnderecoLocalComer.getText().trim();
        int codigo = Integer.parseInt(jTextFieldCodigo.getText().trim());
        try {
            facade.inserirLocalComer(nomeLocalComer, enderecoLocalComer,codigo);
        } catch (CidadeNaoEncontradaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
        
        DefaultTableModel tabela = (DefaultTableModel) jTableLocaisParaComer.getModel();
        
        tabela.addRow (new String [] {nomeLocalComer, enderecoLocalComer}); //Adiciona uma linha com duas colunas;
        jTextFieldNomeDoLocal.setText("Nome do Local");
        jTextFieldEnderecoLocalComer.setText("Endereço do Local");
        
    }//GEN-LAST:event_jButtonAdicionarLocalActionPerformed

    private void jButtonCadastrarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCidadeActionPerformed
        String cidade = jTextFieldCidade.getText().trim();
        int codigo = Integer.parseInt(jTextFieldCodigo.getText().trim());
        double area = Double.parseDouble(jTextFieldArea.getText().trim());
        double populacao = Double.parseDouble(jTextFieldPopulacao.getText().trim());
        int latitude = Integer.parseInt(jTextFieldLatitude.getText().trim());
        int longitude = Integer.parseInt(jTextFieldLongitude.getText().trim());
        String descricao = jTextDescricao.getText().trim();
        
        try {
            facade.inserirCidade(latitude, longitude, area, populacao, descricao, cidade, codigo);
            jTextFieldCidade.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldArea.setEnabled(false);      
            jTextFieldPopulacao.setEnabled(false);
            jTextFieldLatitude.setEnabled(false);   
            jTextFieldLongitude.setEnabled(false);   
            jTextDescricao.setEnabled(false);
            jButtonCadastrarCidade.setEnabled(false);
            jTextFieldNomeDoLocal.setEnabled(true);
            jTextFieldEnderecoLocalComer.setEnabled(true);
            jButtonAdicionarLocal.setEnabled(true);
            jButtonSalvar.setEnabled(true);
        } catch (CidadeDuplicadaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
        
    }//GEN-LAST:event_jButtonCadastrarCidadeActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldLatitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLatitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLatitudeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Cidade cadastrada com sucesso!");
        this.doDefaultCloseAction();
    }//GEN-LAST:event_jButtonSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarLocal;
    private javax.swing.JButton jButtonCadastrarCidade;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLatitude;
    private javax.swing.JLabel jLabelLocalParaComer;
    private javax.swing.JLabel jLabelLongitude;
    private javax.swing.JLabel jLabelPopulacao;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneDescricao;
    private javax.swing.JScrollPane jScrollPaneLocaisParaComer;
    private javax.swing.JTable jTableLocaisParaComer;
    private javax.swing.JTextArea jTextDescricao;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEnderecoLocalComer;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    private javax.swing.JTextField jTextFieldNomeDoLocal;
    private javax.swing.JTextField jTextFieldPopulacao;
    // End of variables declaration//GEN-END:variables
}
