/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.exceptions.UsuarioNaoEncontradoException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_USUARIO_principal extends javax.swing.JFrame {
    private RoadTripsFacade facade;
    private String loginUsuario;
    /**
     * Creates new form RoadTrips_ADM_principal
     */
    public RoadTrips_USUARIO_principal(RoadTripsFacade facade, String loginUsuario) {
        initComponents();
        this.facade = facade;
        this.loginUsuario = loginUsuario;
    }
    public RoadTrips_USUARIO_principal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelIcnMapaRoadTrips = new javax.swing.JLabel();
        jLabelIcnCidade = new javax.swing.JLabel();
        jLabelIcnEstrada = new javax.swing.JLabel();
        JLabelIcnInterseccao = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jComboBoxViagem = new javax.swing.JComboBox<>();
        jComboBoxEstrada = new javax.swing.JComboBox<>();
        jComboBoxInterseccao = new javax.swing.JComboBox<>();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jLabelViagem = new javax.swing.JLabel();
        jLabelIcnUsuario = new javax.swing.JLabel();
        jLabelFundo3 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jLabelFundo1 = new javax.swing.JLabel();
        jLabelFundo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemConsultarCidade = new javax.swing.JMenuItem();
        jMenuItemConsultarEstrada = new javax.swing.JMenuItem();
        jMenuItemConsultarInterseccao = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemRealizarViagem = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemRemoverConta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Road Trips - Usuário");
        setIconImages(null);
        getContentPane().setLayout(null);

        jDesktopPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/logo.gif"))); // NOI18N
        jDesktopPanePrincipal.add(jLabel1);
        jLabel1.setBounds(240, 10, 430, 130);

        jLabelIcnMapaRoadTrips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnMapa2.gif"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelIcnMapaRoadTrips);
        jLabelIcnMapaRoadTrips.setBounds(240, 10, 210, 160);

        jLabelIcnCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnCidade3.jpg"))); // NOI18N
        jLabelIcnCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(jLabelIcnCidade);
        jLabelIcnCidade.setBounds(270, 320, 50, 70);

        jLabelIcnEstrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnEstrada.gif"))); // NOI18N
        jLabelIcnEstrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(jLabelIcnEstrada);
        jLabelIcnEstrada.setBounds(270, 390, 70, 50);

        JLabelIcnInterseccao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/incPlaca.gif"))); // NOI18N
        JLabelIcnInterseccao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(JLabelIcnInterseccao);
        JLabelIcnInterseccao.setBounds(270, 440, 70, 60);

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Opção>", "Consultar Cidade" }));
        jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxCidade);
        jComboBoxCidade.setBounds(340, 350, 180, 20);

        jComboBoxViagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Opção>", "Realizar Viagem" }));
        jComboBoxViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxViagemActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxViagem);
        jComboBoxViagem.setBounds(340, 290, 180, 20);

        jComboBoxEstrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Opção>", "Consultar Estrada" }));
        jComboBoxEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstradaActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxEstrada);
        jComboBoxEstrada.setBounds(340, 410, 180, 20);

        jComboBoxInterseccao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Opção>", "Consultar Intersecção" }));
        jComboBoxInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInterseccaoActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxInterseccao);
        jComboBoxInterseccao.setBounds(340, 470, 180, 20);

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Opção>", "Remover Conta" }));
        jComboBoxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuarioActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxUsuario);
        jComboBoxUsuario.setBounds(340, 530, 180, 20);

        jLabelViagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/viagem.gif"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelViagem);
        jLabelViagem.setBounds(270, 270, 50, 50);

        jLabelIcnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnUsuario.gif"))); // NOI18N
        jLabelIcnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(jLabelIcnUsuario);
        jLabelIcnUsuario.setBounds(270, 500, 60, 50);

        jLabelFundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo3);
        jLabelFundo3.setBounds(0, 0, 626, 390);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo);
        jLabelFundo.setBounds(620, 0, 626, 390);

        jLabelFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo1);
        jLabelFundo1.setBounds(630, 340, 626, 390);

        jLabelFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo2);
        jLabelFundo2.setBounds(0, 390, 620, 290);

        getContentPane().add(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setBounds(0, 0, 860, 670);

        jMenuConsultar.setText("Consultar");

        jMenuItemConsultarCidade.setText("Cidade");
        jMenuItemConsultarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCidadeActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarCidade);

        jMenuItemConsultarEstrada.setText("Estrada");
        jMenuItemConsultarEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarEstradaActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarEstrada);

        jMenuItemConsultarInterseccao.setText("Intersecção");
        jMenuItemConsultarInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarInterseccaoActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarInterseccao);

        jMenuBar1.add(jMenuConsultar);

        jMenuViagem.setText("Viagem");
        jMenuViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuViagemActionPerformed(evt);
            }
        });

        jMenuItemRealizarViagem.setText("Realizar Viagem");
        jMenuItemRealizarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRealizarViagemActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemRealizarViagem);

        jMenuBar1.add(jMenuViagem);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemLogout);

        jMenuItemRemoverConta.setText("Remover Conta");
        jMenuItemRemoverConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverContaActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemRemoverConta);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 868, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        RoadTrips_LOGIN_principal login = new RoadTrips_LOGIN_principal(facade);
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuViagemActionPerformed
    }//GEN-LAST:event_jMenuViagemActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        if(jComboBoxCidade.getSelectedItem().equals("Consultar Cidade")){
            RoadTrips_USUARIO_ConsultarCidade cidade = new RoadTrips_USUARIO_ConsultarCidade(facade);
            jDesktopPanePrincipal.add(cidade);
            cidade.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jMenuItemRealizarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRealizarViagemActionPerformed
        RoadTrips_USUARIO_RealizarViagem viagem = new RoadTrips_USUARIO_RealizarViagem(facade);
        jDesktopPanePrincipal.add(viagem);
        viagem.setVisible(true);
    }//GEN-LAST:event_jMenuItemRealizarViagemActionPerformed

    private void jComboBoxViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxViagemActionPerformed
        if(jComboBoxViagem.getSelectedItem().equals("Realizar Viagem")){
            RoadTrips_USUARIO_RealizarViagem viagem = new RoadTrips_USUARIO_RealizarViagem(facade);
            jDesktopPanePrincipal.add(viagem);
            viagem.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxViagemActionPerformed

    private void jMenuItemConsultarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCidadeActionPerformed
        RoadTrips_USUARIO_ConsultarCidade cidade = new RoadTrips_USUARIO_ConsultarCidade(facade);
        jDesktopPanePrincipal.add(cidade);
        cidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarCidadeActionPerformed

    private void jMenuItemConsultarInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarInterseccaoActionPerformed
        RoadTrips_USUARIO_ConsultarInterseccao interseccao = new RoadTrips_USUARIO_ConsultarInterseccao(facade);
        jDesktopPanePrincipal.add(interseccao);
        interseccao.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarInterseccaoActionPerformed

    private void jComboBoxInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInterseccaoActionPerformed
        if(jComboBoxInterseccao.getSelectedItem().equals("Consultar Intersecção")){
            RoadTrips_USUARIO_ConsultarInterseccao interseccao = new RoadTrips_USUARIO_ConsultarInterseccao(facade);
            jDesktopPanePrincipal.add(interseccao);
            interseccao.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxInterseccaoActionPerformed

    private void jMenuItemConsultarEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarEstradaActionPerformed
        RoadTrips_USUARIO_ConsultarEstrada estrada = new RoadTrips_USUARIO_ConsultarEstrada(facade);
        jDesktopPanePrincipal.add(estrada);
        estrada.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarEstradaActionPerformed

    private void jComboBoxEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstradaActionPerformed
        if(jComboBoxEstrada.getSelectedItem().equals("Consultar Estrada")){
            RoadTrips_USUARIO_ConsultarEstrada estrada = new RoadTrips_USUARIO_ConsultarEstrada(facade);
            jDesktopPanePrincipal.add(estrada);
            estrada.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxEstradaActionPerformed

    private void jComboBoxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioActionPerformed
        if(jComboBoxUsuario.getSelectedItem().equals("Remover Conta")){
            try {
                facade.removerUsuario(loginUsuario);
                JOptionPane.showMessageDialog(rootPane, "Conta removida com sucesso!");
                RoadTrips_LOGIN_principal login = new RoadTrips_LOGIN_principal(facade);
                this.setVisible(false);
                login.setVisible(true);
            } catch (UsuarioNaoEncontradoException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
            }
            
        }
    }//GEN-LAST:event_jComboBoxUsuarioActionPerformed

    private void jMenuItemRemoverContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverContaActionPerformed
        try {
            facade.removerUsuario(loginUsuario);
            JOptionPane.showMessageDialog(rootPane, "Conta removida com sucesso!");
            RoadTrips_LOGIN_principal login = new RoadTrips_LOGIN_principal(facade);
            this.setVisible(false);
            login.setVisible(true);
        } catch (UsuarioNaoEncontradoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jMenuItemRemoverContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_USUARIO_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_USUARIO_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_USUARIO_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_USUARIO_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoadTrips_USUARIO_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelIcnInterseccao;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JComboBox<String> jComboBoxEstrada;
    private javax.swing.JComboBox<String> jComboBoxInterseccao;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JComboBox<String> jComboBoxViagem;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundo1;
    private javax.swing.JLabel jLabelFundo2;
    private javax.swing.JLabel jLabelFundo3;
    private javax.swing.JLabel jLabelIcnCidade;
    private javax.swing.JLabel jLabelIcnEstrada;
    private javax.swing.JLabel jLabelIcnMapaRoadTrips;
    private javax.swing.JLabel jLabelIcnUsuario;
    private javax.swing.JLabel jLabelViagem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuItemConsultarCidade;
    private javax.swing.JMenuItem jMenuItemConsultarEstrada;
    private javax.swing.JMenuItem jMenuItemConsultarInterseccao;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemRealizarViagem;
    private javax.swing.JMenuItem jMenuItemRemoverConta;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuViagem;
    // End of variables declaration//GEN-END:variables
}
