/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.controller.RoadTripsController;
import br.uefs.ecomp.RoadTrips.exceptions.CidadeNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.exceptions.DataNotFoundException;
import br.uefs.ecomp.RoadTrips.exceptions.EstradaDuplicadaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import br.uefs.ecomp.RoadTrips.model.Cidade;
import br.uefs.ecomp.RoadTrips.model.Interseccao;
import br.uefs.ecomp.RoadTrips.model.Ponto;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import java.lang.reflect.Array;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_ADM_CadastrarEstrada extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_ADM_CadastrarEstrada(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
        preencheCidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelCidadeInicial = new javax.swing.JLabel();
        jComboBoxCidadeFinal = new javax.swing.JComboBox<>();
        jComboBoxCidadeInicial = new javax.swing.JComboBox<>();
        jLabelCidadeFinal = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNomeEstrada = new javax.swing.JTextField();
        jLabelDistancia = new javax.swing.JLabel();
        jTextFieldDistancia = new javax.swing.JTextField();
        jButtonCadatrar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Cadastrar Estrada");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelCidadeInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidadeInicial.setText("Ponto Inicial:");
        jPanel2.add(jLabelCidadeInicial);
        jLabelCidadeInicial.setBounds(30, 20, 73, 14);

        jPanel2.add(jComboBoxCidadeFinal);
        jComboBoxCidadeFinal.setBounds(240, 40, 190, 20);

        jComboBoxCidadeInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeInicialActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCidadeInicial);
        jComboBoxCidadeInicial.setBounds(30, 40, 180, 20);

        jLabelCidadeFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidadeFinal.setText("Cidade Final:");
        jPanel2.add(jLabelCidadeFinal);
        jLabelCidadeFinal.setBounds(240, 20, 70, 14);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNome.setText("Nome:");
        jPanel2.add(jLabelNome);
        jLabelNome.setBounds(30, 70, 80, 14);
        jPanel2.add(jTextFieldNomeEstrada);
        jTextFieldNomeEstrada.setBounds(30, 90, 230, 20);

        jLabelDistancia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDistancia.setText("Distância:");
        jPanel2.add(jLabelDistancia);
        jLabelDistancia.setBounds(280, 70, 100, 14);
        jPanel2.add(jTextFieldDistancia);
        jTextFieldDistancia.setBounds(280, 90, 150, 20);

        jButtonCadatrar.setText("Cadastrar Estrada");
        jButtonCadatrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadatrarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCadatrar);
        jButtonCadatrar.setBounds(273, 340, 150, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    public void preencheCidades(){
        jComboBoxCidadeInicial.removeAllItems();
        jComboBoxCidadeInicial.addItem("<Selecionar Opção>");
        jComboBoxCidadeFinal.removeAllItems();
        jComboBoxCidadeFinal.addItem("<Selecionar Opção>");
        
        Iterator itr = facade.iteratorTodasCidade();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Cidade){
                Cidade cidade = (Cidade)o;
                jComboBoxCidadeInicial.addItem(cidade.getNome());
                jComboBoxCidadeFinal.addItem(cidade.getNome());
            }
            else{
                Interseccao interseccao = (Interseccao)o;
                jComboBoxCidadeInicial.addItem(interseccao.getNome());
                jComboBoxCidadeFinal.addItem(interseccao.getNome());
            }
        }
    }
    
    
    private void jComboBoxCidadeInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeInicialActionPerformed
        
    }//GEN-LAST:event_jComboBoxCidadeInicialActionPerformed

    private void jButtonCadatrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadatrarActionPerformed
        Ponto a = null, b = null;
        
        Iterator itr = facade.iteratorTodasCidade();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Cidade){
                Cidade cidade = (Cidade)o;
                if(jComboBoxCidadeInicial.getSelectedItem().equals(cidade.getNome())){
                    a = cidade;
                }
                if(jComboBoxCidadeFinal.getSelectedItem().equals(cidade.getNome())){
                    b = cidade;
                }
            }
            else{
                Interseccao interseccao = (Interseccao)o;
                if(jComboBoxCidadeInicial.getSelectedItem().equals(interseccao.getNome())){
                    a = interseccao;
                }
                if(jComboBoxCidadeFinal.getSelectedItem().equals(interseccao.getNome())){
                    b = interseccao;
                }
            }
        }
        
        String nomeEstrada = jTextFieldNomeEstrada.getText();
        double distancia = Double.parseDouble(jTextFieldDistancia.getText());
        
        try {
            facade.inserirEstrada(a, b, distancia, nomeEstrada);
            JOptionPane.showMessageDialog(rootPane, "Estrada cadastrada com sucesso!");
            this.doDefaultCloseAction();
        } catch (CidadeNaoEncontradaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        } catch (EstradaDuplicadaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jButtonCadatrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadatrar;
    private javax.swing.JComboBox<String> jComboBoxCidadeFinal;
    private javax.swing.JComboBox<String> jComboBoxCidadeInicial;
    private javax.swing.JLabel jLabelCidadeFinal;
    private javax.swing.JLabel jLabelCidadeInicial;
    private javax.swing.JLabel jLabelDistancia;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDistancia;
    private javax.swing.JTextField jTextFieldNomeEstrada;
    // End of variables declaration//GEN-END:variables
}
