/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.exceptions.EstradaNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.exceptions.InterseccaoNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_ADM_RemoverInterseccao extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_ADM_RemoverInterseccao(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNomeInterseccao = new javax.swing.JLabel();
        jTextFieldNomeInterseccao = new javax.swing.JTextField();
        jButtonRemoverInterseccao = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Remover Intersecção");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelNomeInterseccao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNomeInterseccao.setText("Nome Intersecção:");
        jPanel2.add(jLabelNomeInterseccao);
        jLabelNomeInterseccao.setBounds(140, 120, 110, 14);
        jPanel2.add(jTextFieldNomeInterseccao);
        jTextFieldNomeInterseccao.setBounds(140, 140, 160, 20);

        jButtonRemoverInterseccao.setText("Remover ");
        jButtonRemoverInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverInterseccaoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRemoverInterseccao);
        jButtonRemoverInterseccao.setBounds(183, 180, 120, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverInterseccaoActionPerformed
        String nome = jTextFieldNomeInterseccao.getText().trim();
        try {
            facade.removerInterseccao(nome);
            JOptionPane.showMessageDialog(rootPane, "Intersecção removida com sucesso!");
            this.doDefaultCloseAction();
        } catch (InterseccaoNaoEncontradaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jButtonRemoverInterseccaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoverInterseccao;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomeInterseccao;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldNomeInterseccao;
    // End of variables declaration//GEN-END:variables
}
