/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;

/**
 *
 * @author Natalia
 */
public class RoadTrips_ADM_principal extends javax.swing.JFrame {
    private RoadTripsFacade facade;
    /**
     * Creates new form RoadTrips_ADM_principal
     */
    public RoadTrips_ADM_principal(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }
    public RoadTrips_ADM_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelIcnMapaRoadTrips = new javax.swing.JLabel();
        jLabelIcnCidade = new javax.swing.JLabel();
        jLabelIcnEstrada = new javax.swing.JLabel();
        JLabelIcnInterseccao = new javax.swing.JLabel();
        jLabelIcnUsuario = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jComboBoxEstrada = new javax.swing.JComboBox<>();
        jComboBoxInterseccao = new javax.swing.JComboBox<>();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jLabelFundo3 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jLabelFundo1 = new javax.swing.JLabel();
        jLabelFundo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemCadastrarCidade = new javax.swing.JMenuItem();
        jMenuItemCadastrarEstrada = new javax.swing.JMenuItem();
        jMenuItemCadastrarInterseccao = new javax.swing.JMenuItem();
        jMenuRemover = new javax.swing.JMenu();
        jMenuItemRemoverCidade = new javax.swing.JMenuItem();
        jMenuItemRemoverEstrada = new javax.swing.JMenuItem();
        jMenuItemRemoverInsterseccao = new javax.swing.JMenuItem();
        jMenuItemRemoverUsuario = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemCidade = new javax.swing.JMenuItem();
        jMenuItemInterseccao = new javax.swing.JMenuItem();
        jMenuItemEstrada = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Road Trips - Administrador");
        setIconImages(null);
        getContentPane().setLayout(null);

        jDesktopPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/logo.gif"))); // NOI18N
        jDesktopPanePrincipal.add(jLabel1);
        jLabel1.setBounds(240, 10, 430, 130);

        jLabelIcnMapaRoadTrips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnMapa2.gif"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelIcnMapaRoadTrips);
        jLabelIcnMapaRoadTrips.setBounds(240, 10, 210, 160);

        jLabelIcnCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnCidade3.jpg"))); // NOI18N
        jLabelIcnCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(jLabelIcnCidade);
        jLabelIcnCidade.setBounds(270, 260, 50, 70);

        jLabelIcnEstrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnEstrada.gif"))); // NOI18N
        jLabelIcnEstrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(jLabelIcnEstrada);
        jLabelIcnEstrada.setBounds(270, 330, 70, 50);

        JLabelIcnInterseccao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/incPlaca.gif"))); // NOI18N
        JLabelIcnInterseccao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(JLabelIcnInterseccao);
        JLabelIcnInterseccao.setBounds(270, 380, 70, 60);

        jLabelIcnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/icnUsuario.gif"))); // NOI18N
        jLabelIcnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPanePrincipal.add(jLabelIcnUsuario);
        jLabelIcnUsuario.setBounds(270, 450, 60, 50);

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar opção>", "Cadastrar Cidade", "Remover Cidade", "Consultar Cidade" }));
        jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxCidade);
        jComboBoxCidade.setBounds(330, 290, 200, 20);

        jComboBoxEstrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar opção>", "Cadastrar Estrada", "Remover Estrada", "Consultar Estrada" }));
        jComboBoxEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstradaActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxEstrada);
        jComboBoxEstrada.setBounds(330, 350, 200, 20);

        jComboBoxInterseccao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar opção>", "Cadastrar Intersecção", "Remover Intersecção", "Consultar Intersecção" }));
        jComboBoxInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInterseccaoActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxInterseccao);
        jComboBoxInterseccao.setBounds(330, 410, 200, 20);

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Opção>", "Remover Usuário" }));
        jComboBoxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuarioActionPerformed(evt);
            }
        });
        jDesktopPanePrincipal.add(jComboBoxUsuario);
        jComboBoxUsuario.setBounds(330, 470, 200, 20);

        jLabelFundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo3);
        jLabelFundo3.setBounds(0, 0, 626, 390);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo);
        jLabelFundo.setBounds(620, 0, 626, 390);

        jLabelFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo1);
        jLabelFundo1.setBounds(630, 340, 626, 390);

        jLabelFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo.jpg"))); // NOI18N
        jDesktopPanePrincipal.add(jLabelFundo2);
        jLabelFundo2.setBounds(0, 390, 620, 290);

        getContentPane().add(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setBounds(0, 0, 860, 670);

        jMenuCadastrar.setText("Cadastrar");

        jMenuItemCadastrarCidade.setText("Cidade");
        jMenuItemCadastrarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarCidadeActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadastrarCidade);

        jMenuItemCadastrarEstrada.setText("Estrada");
        jMenuItemCadastrarEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarEstradaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadastrarEstrada);

        jMenuItemCadastrarInterseccao.setText("Intersecção");
        jMenuItemCadastrarInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarInterseccaoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadastrarInterseccao);

        jMenuBar1.add(jMenuCadastrar);

        jMenuRemover.setText("Remover");

        jMenuItemRemoverCidade.setText("Cidade");
        jMenuItemRemoverCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverCidadeActionPerformed(evt);
            }
        });
        jMenuRemover.add(jMenuItemRemoverCidade);

        jMenuItemRemoverEstrada.setText("Estrada");
        jMenuItemRemoverEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverEstradaActionPerformed(evt);
            }
        });
        jMenuRemover.add(jMenuItemRemoverEstrada);

        jMenuItemRemoverInsterseccao.setText("Intersecção");
        jMenuItemRemoverInsterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverInsterseccaoActionPerformed(evt);
            }
        });
        jMenuRemover.add(jMenuItemRemoverInsterseccao);

        jMenuItemRemoverUsuario.setText("Usuário");
        jMenuItemRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverUsuarioActionPerformed(evt);
            }
        });
        jMenuRemover.add(jMenuItemRemoverUsuario);

        jMenuBar1.add(jMenuRemover);

        jMenuConsultar.setText("Consultar");

        jMenuItemCidade.setText("Cidade");
        jMenuItemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCidadeActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemCidade);

        jMenuItemInterseccao.setText("Intersecção");
        jMenuItemInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInterseccaoActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemInterseccao);

        jMenuItemEstrada.setText("Estrada");
        jMenuItemEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstradaActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemEstrada);

        jMenuBar1.add(jMenuConsultar);

        jMenuSair.setText("Sair");
        jMenuSair.setToolTipText("");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemLogout);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 868, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarCidadeActionPerformed
        RoadTrips_ADM_CadastrarCidade cadastrarCidade = new RoadTrips_ADM_CadastrarCidade(facade);
        jDesktopPanePrincipal.add(cadastrarCidade);
        cadastrarCidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarCidadeActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        if(jComboBoxCidade.getSelectedItem().equals("Cadastrar Cidade")){
            RoadTrips_ADM_CadastrarCidade cadastrarCidade = new RoadTrips_ADM_CadastrarCidade(facade);
            jDesktopPanePrincipal.add(cadastrarCidade);
            cadastrarCidade.setVisible(true);
        }
        
        if(jComboBoxCidade.getSelectedItem().equals("Remover Cidade")){
            RoadTrips_ADM_RemoverCidade removerCidade = new RoadTrips_ADM_RemoverCidade(facade);
            jDesktopPanePrincipal.add(removerCidade);
            removerCidade.setVisible(true);
        }
        
        if(jComboBoxCidade.getSelectedItem().equals("Consultar Cidade")){
            RoadTrips_USUARIO_ConsultarCidade cidade = new RoadTrips_USUARIO_ConsultarCidade(facade);
            jDesktopPanePrincipal.add(cidade);
            cidade.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jMenuItemRemoverCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverCidadeActionPerformed
        RoadTrips_ADM_RemoverCidade removerCidade = new RoadTrips_ADM_RemoverCidade(facade);
        jDesktopPanePrincipal.add(removerCidade);
        removerCidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverCidadeActionPerformed

    private void jComboBoxEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstradaActionPerformed
        if(jComboBoxEstrada.getSelectedItem().equals("Cadastrar Estrada")){
            RoadTrips_ADM_CadastrarEstrada cadastrarEstrada = new RoadTrips_ADM_CadastrarEstrada(facade);
            jDesktopPanePrincipal.add(cadastrarEstrada);
            cadastrarEstrada.setVisible(true);
        }
        
        if(jComboBoxEstrada.getSelectedItem().equals("Remover Estrada")){
            RoadTrips_ADM_RemoverEstrada removerEstrada = new RoadTrips_ADM_RemoverEstrada(facade);
            jDesktopPanePrincipal.add(removerEstrada);
            removerEstrada.setVisible(true);
        }
        
        if(jComboBoxEstrada.getSelectedItem().equals("Consultar Estrada")){
            RoadTrips_USUARIO_ConsultarEstrada estrada = new RoadTrips_USUARIO_ConsultarEstrada(facade);
            jDesktopPanePrincipal.add(estrada);
            estrada.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxEstradaActionPerformed

    private void jMenuItemCadastrarEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarEstradaActionPerformed
        RoadTrips_ADM_CadastrarEstrada cadastrarEstrada = new RoadTrips_ADM_CadastrarEstrada(facade);
        jDesktopPanePrincipal.add(cadastrarEstrada);
        cadastrarEstrada.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarEstradaActionPerformed

    private void jMenuItemRemoverEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverEstradaActionPerformed
        RoadTrips_ADM_RemoverEstrada removerEstrada = new RoadTrips_ADM_RemoverEstrada(facade);
        jDesktopPanePrincipal.add(removerEstrada);
        removerEstrada.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverEstradaActionPerformed

    private void jComboBoxInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInterseccaoActionPerformed
        if(jComboBoxInterseccao.getSelectedItem().equals("Cadastrar Intersecção")){
            RoadTrips_ADM_CadastrarInterseccao cadastrarInterseccao = new RoadTrips_ADM_CadastrarInterseccao(facade);
            jDesktopPanePrincipal.add(cadastrarInterseccao);
            cadastrarInterseccao.setVisible(true);
        }
        
        if(jComboBoxInterseccao.getSelectedItem().equals("Remover Intersecção")){
            RoadTrips_ADM_RemoverInterseccao removerInterseccao = new RoadTrips_ADM_RemoverInterseccao(facade);
            jDesktopPanePrincipal.add(removerInterseccao);
            removerInterseccao.setVisible(true);
        }
        
        if(jComboBoxInterseccao.getSelectedItem().equals("Consultar Intersecção")){
            RoadTrips_USUARIO_ConsultarInterseccao interseccao = new RoadTrips_USUARIO_ConsultarInterseccao(facade);
            jDesktopPanePrincipal.add(interseccao);
            interseccao.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxInterseccaoActionPerformed

    private void jMenuItemCadastrarInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarInterseccaoActionPerformed
        RoadTrips_ADM_CadastrarInterseccao cadastrarInterseccao = new RoadTrips_ADM_CadastrarInterseccao(facade);
        jDesktopPanePrincipal.add(cadastrarInterseccao);
        cadastrarInterseccao.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarInterseccaoActionPerformed

    private void jMenuItemRemoverInsterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverInsterseccaoActionPerformed
        RoadTrips_ADM_RemoverInterseccao removerInterseccao = new RoadTrips_ADM_RemoverInterseccao(facade);
        jDesktopPanePrincipal.add(removerInterseccao);
        removerInterseccao.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverInsterseccaoActionPerformed

    private void jMenuItemRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverUsuarioActionPerformed
        RoadTrips_ADM_RemoverUsuario removerUsuario = new RoadTrips_ADM_RemoverUsuario(facade);
        jDesktopPanePrincipal.add(removerUsuario);
        removerUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverUsuarioActionPerformed

    private void jComboBoxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioActionPerformed
        if(jComboBoxUsuario.getSelectedItem().equals("Remover Usuário")){
            RoadTrips_ADM_RemoverUsuario removerUsuario = new RoadTrips_ADM_RemoverUsuario(facade);
            jDesktopPanePrincipal.add(removerUsuario);
            removerUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxUsuarioActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        RoadTrips_LOGIN_principal login = new RoadTrips_LOGIN_principal(facade);
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadeActionPerformed
        RoadTrips_USUARIO_ConsultarCidade cidade = new RoadTrips_USUARIO_ConsultarCidade(facade);
        jDesktopPanePrincipal.add(cidade);
        cidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemCidadeActionPerformed

    private void jMenuItemInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInterseccaoActionPerformed
        RoadTrips_USUARIO_ConsultarInterseccao interseccao = new RoadTrips_USUARIO_ConsultarInterseccao(facade);
        jDesktopPanePrincipal.add(interseccao);
        interseccao.setVisible(true);
    }//GEN-LAST:event_jMenuItemInterseccaoActionPerformed

    private void jMenuItemEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstradaActionPerformed
        RoadTrips_USUARIO_ConsultarEstrada estrada = new RoadTrips_USUARIO_ConsultarEstrada(facade);
        jDesktopPanePrincipal.add(estrada);
        estrada.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_ADM_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_ADM_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_ADM_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoadTrips_ADM_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoadTrips_ADM_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelIcnInterseccao;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JComboBox<String> jComboBoxEstrada;
    private javax.swing.JComboBox<String> jComboBoxInterseccao;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundo1;
    private javax.swing.JLabel jLabelFundo2;
    private javax.swing.JLabel jLabelFundo3;
    private javax.swing.JLabel jLabelIcnCidade;
    private javax.swing.JLabel jLabelIcnEstrada;
    private javax.swing.JLabel jLabelIcnMapaRoadTrips;
    private javax.swing.JLabel jLabelIcnUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuItemCadastrarCidade;
    private javax.swing.JMenuItem jMenuItemCadastrarEstrada;
    private javax.swing.JMenuItem jMenuItemCadastrarInterseccao;
    private javax.swing.JMenuItem jMenuItemCidade;
    private javax.swing.JMenuItem jMenuItemEstrada;
    private javax.swing.JMenuItem jMenuItemInterseccao;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemRemoverCidade;
    private javax.swing.JMenuItem jMenuItemRemoverEstrada;
    private javax.swing.JMenuItem jMenuItemRemoverInsterseccao;
    private javax.swing.JMenuItem jMenuItemRemoverUsuario;
    private javax.swing.JMenu jMenuRemover;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
