/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.exceptions.EstradaNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_ADM_RemoverEstrada extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_ADM_RemoverEstrada(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNomeEstrada = new javax.swing.JLabel();
        jTextFieldNomeEstrada = new javax.swing.JTextField();
        jButtonRemoverEstrada = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Remover Estrada");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelNomeEstrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNomeEstrada.setText("Nome Estrada:");
        jPanel2.add(jLabelNomeEstrada);
        jLabelNomeEstrada.setBounds(140, 120, 110, 14);
        jPanel2.add(jTextFieldNomeEstrada);
        jTextFieldNomeEstrada.setBounds(140, 140, 160, 20);

        jButtonRemoverEstrada.setText("Remover ");
        jButtonRemoverEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverEstradaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRemoverEstrada);
        jButtonRemoverEstrada.setBounds(183, 180, 120, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverEstradaActionPerformed
        String nome = jTextFieldNomeEstrada.getText().trim();
        
        try {
            facade.removerEstrada(nome);
            JOptionPane.showMessageDialog(rootPane, "Estrada removida com sucesso!");
            this.doDefaultCloseAction();
        } catch (EstradaNaoEncontradaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jButtonRemoverEstradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoverEstrada;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomeEstrada;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldNomeEstrada;
    // End of variables declaration//GEN-END:variables
}
