/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.exceptions.CidadeNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_ADM_RemoverCidade extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_ADM_RemoverCidade(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelCodigoCidade = new javax.swing.JLabel();
        jTextFieldCodigoCidade = new javax.swing.JTextField();
        jButtonRemoverCidade = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Remover Cidade");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelCodigoCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCodigoCidade.setText("Código:");
        jPanel2.add(jLabelCodigoCidade);
        jLabelCodigoCidade.setBounds(140, 120, 70, 14);
        jPanel2.add(jTextFieldCodigoCidade);
        jTextFieldCodigoCidade.setBounds(140, 140, 160, 20);

        jButtonRemoverCidade.setText("Remover ");
        jButtonRemoverCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverCidadeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRemoverCidade);
        jButtonRemoverCidade.setBounds(203, 180, 100, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverCidadeActionPerformed
        int codigo = Integer.parseInt(jTextFieldCodigoCidade.getText().trim());
        try {
            facade.removerCidade(codigo);
            JOptionPane.showMessageDialog(rootPane, "Cidade Removida com sucesso!");
            this.doDefaultCloseAction();
        } catch (CidadeNaoEncontradaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jButtonRemoverCidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoverCidade;
    private javax.swing.JLabel jLabelCodigoCidade;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCodigoCidade;
    // End of variables declaration//GEN-END:variables
}
