/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import br.uefs.ecomp.RoadTrips.model.Interseccao;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_USUARIO_ConsultarInterseccao extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_USUARIO_ConsultarInterseccao(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
        preencheCidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelInterseccao = new javax.swing.JLabel();
        jComboBoxInterseccao = new javax.swing.JComboBox<>();
        jButtonConsultar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Consultar Intersecção");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelInterseccao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInterseccao.setText("Intersecção:");
        jPanel2.add(jLabelInterseccao);
        jLabelInterseccao.setBounds(30, 20, 120, 14);

        jComboBoxInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInterseccaoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxInterseccao);
        jComboBoxInterseccao.setBounds(30, 40, 400, 20);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConsultar);
        jButtonConsultar.setBounds(293, 340, 130, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    public void preencheCidades(){
        jComboBoxInterseccao.removeAllItems();
        jComboBoxInterseccao.addItem("<Selecionar Opção>");
        
        Iterator itr = facade.iteratorTodasCidade();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Interseccao){
                Interseccao interseccao = (Interseccao)o;
                jComboBoxInterseccao.addItem(interseccao.getNome());
            }
        }
    }
    
    
    private void jComboBoxInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInterseccaoActionPerformed
        
    }//GEN-LAST:event_jComboBoxInterseccaoActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        Iterator itr = facade.iteratorTodasCidade();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Interseccao){
                Interseccao interseccao = (Interseccao)o;
                if(jComboBoxInterseccao.getSelectedItem().equals(interseccao.getNome())){
                    JOptionPane.showMessageDialog(rootPane, "Nome: "+interseccao.getNome()+"\n"
                                                           +"Latitude: "+interseccao.getLatitude()+"\n"
                                                           +"Longitude: "+interseccao.getLongitude()+"\n"
                            
                    );
                }
            }
        }
        
    }//GEN-LAST:event_jButtonConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JComboBox<String> jComboBoxInterseccao;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelInterseccao;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
