/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.controller.RoadTripsController;
import br.uefs.ecomp.RoadTrips.exceptions.CidadeNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.exceptions.DataNotFoundException;
import br.uefs.ecomp.RoadTrips.exceptions.EstradaDuplicadaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import br.uefs.ecomp.RoadTrips.model.Cidade;
import br.uefs.ecomp.RoadTrips.model.Estrada;
import br.uefs.ecomp.RoadTrips.model.Interseccao;
import br.uefs.ecomp.RoadTrips.model.Ponto;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import java.lang.reflect.Array;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_USUARIO_ConsultarEstrada extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_USUARIO_ConsultarEstrada(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
        preencheEstradas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelEstrada = new javax.swing.JLabel();
        jComboBoxEstrada = new javax.swing.JComboBox<>();
        jButtonConsultar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Consultar Estrada");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelEstrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEstrada.setText("Estrada:");
        jPanel2.add(jLabelEstrada);
        jLabelEstrada.setBounds(30, 20, 120, 14);

        jComboBoxEstrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstradaActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxEstrada);
        jComboBoxEstrada.setBounds(30, 40, 400, 20);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConsultar);
        jButtonConsultar.setBounds(293, 340, 130, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    public void preencheEstradas(){
        jComboBoxEstrada.removeAllItems();
        jComboBoxEstrada.addItem("<Selecionar Opção>");
        
        Iterator itr = facade.iteratorTodasArestas();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Estrada){
                Estrada estrada = (Estrada)o;
                jComboBoxEstrada.addItem(estrada.getNome());
            }
        }
    }
    
    
    private void jComboBoxEstradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstradaActionPerformed
        
    }//GEN-LAST:event_jComboBoxEstradaActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        Iterator itr = facade.iteratorTodasArestas();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Estrada){
                Estrada estrada = (Estrada)o;
                if(jComboBoxEstrada.getSelectedItem().equals(estrada.getNome())){
                    String nomeA, nomeB;
                    if(estrada.getSource() instanceof Cidade){
                        nomeA = ((Cidade)estrada.getSource()).getNome();
                    }
                    else{
                        nomeA = ((Interseccao)estrada.getSource()).getNome();
                    }
                    
                    if(estrada.getDestiny() instanceof Cidade){
                        nomeB = ((Cidade)estrada.getDestiny()).getNome();
                    }
                    else{
                        nomeB = ((Interseccao)estrada.getDestiny()).getNome();
                    }
                    
                    JOptionPane.showMessageDialog(rootPane, "Nome: "+estrada.getNome()+"\n"
                                                           +"Ponto Inicial: "+nomeA+"\n"
                                                           +"Ponto Final: "+nomeB+"\n"
                                                           +"Distância: "+estrada.getWeight()+"\n"
                    );
                }
            }
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JComboBox<String> jComboBoxEstrada;
    private javax.swing.JLabel jLabelEstrada;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
