/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.RoadTrips.view;

import br.uefs.ecomp.RoadTrips.controller.RoadTripsController;
import br.uefs.ecomp.RoadTrips.exceptions.CidadeNaoEncontradaException;
import br.uefs.ecomp.RoadTrips.exceptions.DataNotFoundException;
import br.uefs.ecomp.RoadTrips.exceptions.EstradaDuplicadaException;
import br.uefs.ecomp.RoadTrips.exceptions.InterseccaoDuplicadaException;
import br.uefs.ecomp.RoadTrips.facade.RoadTripsFacade;
import br.uefs.ecomp.RoadTrips.model.Cidade;
import br.uefs.ecomp.RoadTrips.model.Interseccao;
import br.uefs.ecomp.RoadTrips.model.Ponto;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import java.lang.reflect.Array;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class RoadTrips_ADM_CadastrarInterseccao extends javax.swing.JInternalFrame {
    private RoadTripsFacade facade;
    
    /**
     * Creates new form RoadTrips_ADM_CadastrarCidade
     */
    public RoadTrips_ADM_CadastrarInterseccao(RoadTripsFacade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelLatitude = new javax.swing.JLabel();
        jLabelLongitude = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldLongitude = new javax.swing.JTextField();
        jTextFieldLatitude = new javax.swing.JTextField();
        jButtonCadatrar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Cadastrar Intersecção");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabelLatitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLatitude.setText("Latitude:");
        jPanel2.add(jLabelLatitude);
        jLabelLatitude.setBounds(30, 20, 50, 14);

        jLabelLongitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLongitude.setText("Longitude:");
        jPanel2.add(jLabelLongitude);
        jLabelLongitude.setBounds(240, 20, 59, 14);

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipo.setText("Tipo:");
        jPanel2.add(jLabelTipo);
        jLabelTipo.setBounds(30, 70, 80, 14);
        jPanel2.add(jTextFieldTipo);
        jTextFieldTipo.setBounds(30, 90, 230, 20);
        jPanel2.add(jTextFieldLongitude);
        jTextFieldLongitude.setBounds(240, 40, 190, 20);
        jPanel2.add(jTextFieldLatitude);
        jTextFieldLatitude.setBounds(30, 40, 190, 20);

        jButtonCadatrar.setText("Cadastrar Intersecção");
        jButtonCadatrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadatrarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCadatrar);
        jButtonCadatrar.setBounds(233, 340, 190, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/RoadTrips/imagens/fundo2.jpg"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 410);

        setBounds(175, 200, 470, 439);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonCadatrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadatrarActionPerformed
        int latitude = Integer.parseInt(jTextFieldLatitude.getText());
        int longitude = Integer.parseInt(jTextFieldLongitude.getText());
        String tipo = jTextFieldTipo.getText();
        try {
            facade.inserirInterseccao(latitude, longitude, tipo);
            JOptionPane.showMessageDialog(rootPane, "Intersecção cadastrada com sucesso!");
            this.doDefaultCloseAction();
        } catch (InterseccaoDuplicadaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMensagem());
        }
    }//GEN-LAST:event_jButtonCadatrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadatrar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLatitude;
    private javax.swing.JLabel jLabelLongitude;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
